### ISSUE TITLE
container issues

### ISSUE THREAD

**Issue by luismanson** [jdortuzar5/movie-recommender#1]
Hello I want to check the working code but one of the containers wont work, it keeps saying:
`tensorflow-servings_1  | 2021-01-18 17:34:00.493553: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:267] No versions of servable movie_model found under base path /models/movie_model. Did you forget to name your leaf directory as a number (eg. '/1/')?`

I have no idea what it means.

**Comment by jdortuzar5** [comment]
Hi, this error means that Tensorflow Serving could not find a trained model in the `ai_model` directory. Did you train a model? if you did, is it under the `ai_model` directory?

**Comment by luismanson** [comment]
Thanks, I apologize since did not read all.

Now i get a white screen from the frontend. I see 404 on _/build/bundle.js_ from the frontend container. I got inside the container an executed "rollup -c", generated files are in /public/build/ but I still get 404.

Sorry if this is something obvious.

**Comment by jdortuzar5** [comment]
No problem, we are all learning.
I pushed a fix on master for the _/build/bundle.js_ issue, you should pull the repo and just to be sure run `docker-compose up --build`. 
The problem was a missing command in the frontend Dockerfile. So the missing file was not being build by the container.
It was not an obvious problem so thanks a lot for pointing it out.

**Comment by luismanson** [comment]
It works now, thanks!
